openapi: 3.1.0
info:
  title: Import Product From AI
  description: Posts parsed plan and product data to the ImportProductFromAI endpoint.
  version: v1.0.1
servers:
  - url: https://relaxed-chebyshev.92-205-27-128.plesk.page
paths:
  /Home/ImportProductFromAI:
    post:
      summary: Send parsed mortgage plan data to API
      operationId: importProductFromAI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Plans:
                  type: array
                  items:
                    type: object
                    properties:
                      Lender:
                        type: string
                      PlanName:
                        type: string
                      Products:
                        type: array
                        items:
                          type: object
      responses:
        "200":
          description: Successful import
        "400":
          description: Bad request or invalid JSON
        "500":
          description: Server error
